# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            i.am.rolandw
tagline:          An English technologist
url:              http://iam.rolandw.me
paginate:         1
baseurl:          /
author:
  name:           Roland Whitehead
  url:            https://twitter.com/rolandw
  email:          i.am@rolandw.me
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/atom.xml'


# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/iamrolandw/iamrolandw
